os: osx
language: node_js
node_js: node
install:
- npm install
script:
- npm run test
before_deploy:
- brew update
- brew install wine mono  gnu-tar graphicsmagick xz
- npm run build
deploy:
  provider: releases
  api_key:
    secure: mL2CKY5DSjwcrX2xvo6l9lrkUrxYky3OE9HK7HsxZ6s3XUrRyXQO/472Bamo7CKXwyfUa/48L1OAC41R6VTQ2A3c/AJo6PrXPv9d2lZ4icomf5ocovF+DWmtVXnW1wIY48mv0xmB/iqTSDqoV/DBFnbQgY7y7W5CBJY3gjNLrtfdKw+dJbOOJMN77R8SjGBa1PU7WqnNAhidbX2DitFM9OBIj05o6lvBkbFjM5fVV77lfV5jrSXTweHF6Kq7Puv8iODNHTYtF7YF58VI4sI4gNHd/HSUscjr3Wl+jIcrqZBtzxdbyN6WpWIzVBOyjismQrefsfhX+fajzkIHS5Jizw9ObuP8PRdDRzL34W2IngsOF78j5AuslbSStLccqYjBmzDBmVvY/N5QXgCGauMIWjfYv2s822+Yw9yUaYEWEbfAwbpxlcqrNu85bA1H+h3J85gNqz9HaUJDadtpapZLm9w4byLAGUelJo2D/1UDyLFPy3cECI5ajQ4jnnDu+4v0bmZuGhpstT93QEYhfoxfFy0t2gPpkyOIzB3MrW3tDkPzOyR2DHh09TirqstVBmGa4aNvbcNObxHGTcgl2vWUPG0tgEvM7AFZ/qnpNkYaHMrUmhPgdKKYA42Ydyu7EjnPuDW+jtt4QcY4ingoSXGWZbAFmKfyBm6VdNUZjDsetes=
  file_glob: true
  file: 'dist/*.{dmg,AppImage,exe}'
  on:
    tags: true
    repo: ta2gch/yomu
env:
  global:
    secure: PolFGPP7geB2ht6niCDB6CM/0YE0guaLid0YW/oRrTIAComo2Lf/0nfxuK7PitLiV2u9pL8kXCKxy/d1E19TNYwHtNF/XghZSxgyS3/v8lXUp3gm43Xu9LylWwt5KdniRrVbsOiOv4OZaan1A6FdCArbjrHnTjPJQFlssP/3yKJyKroJ1A2Wl1759YNux0nf3ZXwR4t6+Bliswu12/KRVgewmPUz3ecSGwP7YMFjZyH1WHJ1m/IvUEqfgVIpUi0MA3DYJbsdGT5d7ou7BGfDBn8V4Y/+SthiVnOk37PSCcZsnyRmX0Vad0WGmY9N+3q0K07lQtkXHZA4dy1hBkXqkmEaB+OY6nD1el4TIvHrru97TDmwmVxaidux+WQzX0F7fjJjHJCfTKKRtx1EHvLMnjFdipRX9uAXihDOcQm2bVri+K60+8PYfFgI+akc6ydV4R+DcvauXFbkMSRQ1JVPxdJ/OaiB3fbEohmnKNCo+SIv00CePBiJGAeG93RGQDaTIkW0YVSfyar2iSWCthnvMHbS3fhHvc/AvpTNcXjwoZPccovx3vxxTgqC6SNPwCLNjNBGdIFFVfUxmjLZYL+2bRkl0HW48AimG5DSzN15RHXOW+aGQ0eX2SbAXRpsl+U6xI/xd6wck+7C+HCANXTSMsOZAafFttqt7xetb0fP9gE=
